services:
  - type: web
    name: sigmaplus
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: sigmaplus-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: sigmaplus-mongodb
    plan: free
    databaseName: sigmaplus
    ipAllowList: [] # Allows connections from anywhere

